create consumable
Jordan-Renaud/discworld-dnd pull request #12
Opened 2022-07-03 10:42 UTC by Darth-Knoppix

Closes #11

2022-07-22 09:19 UTC, Jordan-Renaud requested changes

2022-07-22 09:19 UTC, Jordan-Renaud commented on prisma/schema.prisma
> +model ConsumableType {
change to ConsumablePrototype

2022-07-24 08:07 UTC, Darth-Knoppix commented
Uses prototype suffix, ready to re-review

2022-08-01 10:44 UTC, Jordan-Renaud approved these changes

2022-08-01 10:45 UTC, merged